on: 
    push:
        branches:
          - "GithubLearn"
    pull_request: 
      branches: 
        - main
        - release/*

jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v2
        - name: Build docker image
          run: |
            docker build -t my-image .  
        - name: Run container with API key
          run: |
            docker run --name my-container -e OPENAI_API_KEY=${{secrets.OPENAI_API_KEY}} my-imagetet


