on: 
    push:
        branches:
          - "ryc0051-patch-1"
    pull_request: 
      branches: 
        - main
        - release/*
jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - name: Make Environment
          run: make env
        - name: Lint file
          run: make lint
        - name: Execute file
          run : make run

